name: "scrape_as_a_service"
services:
  #==================
  #   KAFKA
  #==================
  # Ingestion pipeline
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      
      # Listener setup
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - app_network
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: always
    ports:
      # Minio also uses 9000 by default
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    networks:
      - app_network
  
  #==================
  #   REDIS
  #==================
  # Ingestion Pipeline AND Scrape Completion notifications
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app_network
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - app_network
    # NOTE: add Redis Database | "Connection Settings" | update Host to "redis" to connect to Redis container instead of host machine
  
  #==================
  #   MINIO
  #==================
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9002:9002"  # API
      - "9003:9003"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9003" /data

volumes:
  kafka_data:
  minio-data:
  redis-insight:

networks:
  app_network:
    driver: bridge
