# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scrape_task.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'scrape_task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11scrape_task.proto\"\xfa\x01\n\nScrapeTask\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12)\n\x07headers\x18\x04 \x03(\x0b\x32\x18.ScrapeTask.HeadersEntry\x12\'\n\x06params\x18\x05 \x03(\x0b\x32\x17.ScrapeTask.ParamsEntry\x12\x0c\n\x04\x62ody\x18\x06 \x01(\t\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scrape_task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRAPETASK_HEADERSENTRY']._loaded_options = None
  _globals['_SCRAPETASK_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_SCRAPETASK_PARAMSENTRY']._loaded_options = None
  _globals['_SCRAPETASK_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_SCRAPETASK']._serialized_start=22
  _globals['_SCRAPETASK']._serialized_end=272
  _globals['_SCRAPETASK_HEADERSENTRY']._serialized_start=179
  _globals['_SCRAPETASK_HEADERSENTRY']._serialized_end=225
  _globals['_SCRAPETASK_PARAMSENTRY']._serialized_start=227
  _globals['_SCRAPETASK_PARAMSENTRY']._serialized_end=272
# @@protoc_insertion_point(module_scope)
